# EXERCISES & EXTRA-CURRICULUM

## Create a random tensor with shape (7, 7).

In [ ]:
import torch

random_tensor = torch.rand(7, 7) # Create a random tensor of shape (7, 7)
random_tensor, random_tensor.shape # Display the tensor and its shape

(tensor([[0.6194, 0.3328, 0.2031, 0.1166, 0.6806, 0.8945, 0.3589],
         [0.3589, 0.7869, 0.3559, 0.4835, 0.7552, 0.9075, 0.0115],
         [0.9720, 0.6000, 0.3438, 0.7700, 0.5022, 0.5358, 0.7880],
         [0.1588, 0.0860, 0.9809, 0.4813, 0.9212, 0.3789, 0.8227],
         [0.6995, 0.3346, 0.2459, 0.0436, 0.5606, 0.5592, 0.3525],
         [0.4972, 0.3134, 0.9224, 0.2705, 0.9129, 0.1048, 0.7756],
         [0.2237, 0.4968, 0.5769, 0.4101, 0.1658, 0.8544, 0.6586]]),
 torch.Size([7, 7]))

## Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

Cant matmul `(7, 7) @ (1, 7)` because inner dimensions dont match. Must first transpose either to make inner dimensions match.

In [26]:
random_tensor2 = torch.rand(1, 7)
random_tensor2, random_tensor2.shape # Create another random tensor of shape (1, 7) and display it

random_tensor2_transposed = random_tensor2.transpose(0, 1) # Transpose the second tensor to shape (7, 1)

t1t2 = torch.matmul(random_tensor, random_tensor2_transposed) # Perform matrix multiplication between the two tensors

t1t2, t1t2.shape # Display the result of the multiplication and its shape

(tensor([[1.2741],
         [1.4061],
         [2.0522],
         [1.8029],
         [1.4137],
         [1.7786],
         [1.0244]]),
 torch.Size([7, 1]))

## Set the random seed to 0 and do exercises 2 & 3 over again.

In [17]:
import torch

seed = 0 # Set a seed for reproducibility

torch.manual_seed(seed) # Apply the seed to PyTorch's random number generator
random_tensor = torch.rand(7, 7) # Create a new random tensor of shape (7, 7)
random_tensor, random_tensor.shape # Display the new tensor and its shape



(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 torch.Size([7, 7]))

In [20]:
torch.manual_seed(seed) # Reset the seed for reproducibility
random_tensor2 = torch.rand(1, 7) # Create another random tensor of shape (7, 7)
random_tensor2, random_tensor2.shape # Display the second tensor and its shape

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 torch.Size([1, 7]))

In [22]:
random_tensor2_transposed = random_tensor2.transpose(0, 1) # Transpose the second tensor to shape (7, 1)
random_tensor2_transposed, random_tensor2_transposed.shape # Display the transposed tensor and its shape

(tensor([[0.4963],
         [0.7682],
         [0.0885],
         [0.1320],
         [0.3074],
         [0.6341],
         [0.4901]]),
 torch.Size([7, 1]))

In [31]:
T1T1 = random_tensor @ random_tensor2_transposed # Perform matrix multiplication between the first tensor and the transposed second tensor
T1T1, T1T1.shape, T1T1.device # Display the result of the multiplication and its shape

(tensor([[1.2741],
         [1.4061],
         [2.0522],
         [1.8029],
         [1.4137],
         [1.7786],
         [1.0244]]),
 torch.Size([7, 1]),
 device(type='cpu'))

## Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [ ]:
import torch

random_gpu_seed = 1234 # Set a seed for reproducibility on GPU
torch.cuda.manual_seed(random_gpu_seed) # Apply the seed to PyTorch's GPU random number generator

## Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [61]:
# Create 2 random tensors of same shape

# Set manual_seed to 1234 for reproducibility
torch.manual_seed(1234)
tensor_A = torch.rand(2, 3, device='cuda')  # Create a random tensor on GPU
tensor_B = torch.rand(2, 3, device='cuda')  # Create another random tensor on GPU

# Display the tensors and devices
print(f'tensor_A: \n{tensor_A}', 
      f'\ntensor_B: \n{tensor_B}')  

# Print tenosr shape
print(f'\ntensor_A device: {tensor_A.shape}',
      f'\ntensor_B device: {tensor_B.shape}')

tensor_A: 
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') 
tensor_B: 
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')

tensor_A device: torch.Size([2, 3]) 
tensor_B device: torch.Size([2, 3])


## Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [66]:
import torch

tensor_A_T = tensor_A.transpose(0, 1) # Transpose tensor_A to shape (3, 2)

AB = torch.matmul(tensor_A_T, tensor_B)
AB, AB.shape

(tensor([[0.1525, 0.4531, 0.2796],
         [0.5374, 0.2079, 0.3640],
         [0.4462, 0.6783, 0.5284]], device='cuda:0'),
 torch.Size([3, 3]))

## Find the maximum and minimum values of the output of 7.

In [ ]:
# .max() and .min() methods to find the maximum and minimum values in the given tensor
print(f'AB max: {AB.max()}',
      f'\nAB min: {AB.min()}',)

AB max: 0.6782569885253906 
AB min: 0.152530238032341


## Find the maximum and minimum index values of the output of 7.

In [74]:
# argmax() and argmin() methods to find the indices of the maximum and minimum values in the tensor
print(f'AB max Index: {AB.argmax()}',
      f'\nAB min: {AB.argmin()}',)

AB max Index: 7 
AB min: 0


## Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [88]:
# set a manual seed for reproducibility
torch.manual_seed(7)

tensor = torch.rand(1, 1, 1, 10)
tensor, tensor.shape 

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [87]:
# Remove dimensions of size 1 from the tensor
new_tensor = tensor.squeeze() 

# Display the new tensor and its shape
new_tensor, new_tensor.shape 

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

## RANDOM TENSOR PRACTICE

In [94]:
import torch
import numpy as np

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)  # Convert a list to a PyTorch tensor

x_data, x_data.shape, x_data.dtype  # Display the tensor and its shape

(tensor([[1, 2],
         [3, 4]]),
 torch.Size([2, 2]),
 torch.int64)

In [101]:
x_ones = torch.ones_like(x_data)  # Create a tensor of ones with the same shape as x_data
print(f'x_ones: \n{x_ones}')

x_rand = torch.rand_like(x_data,dtype=torch.float32 ) # Create a tensor of random values with the same shape as x_data
print(f'x_rand: \n{x_rand}')

x_ones: 
tensor([[1, 1],
        [1, 1]])
x_rand: 
tensor([[0.9699, 0.1078],
        [0.8829, 0.4132]])


In [122]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5643, 0.3347, 0.0358],
        [0.1494, 0.5271, 0.4732]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
