In [6]:
print("Hello world, lets start playing with pytorch!")

Hello world, lets start playing with pytorch!


In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)
print(torch.version.cuda)
torch.cuda.is_available()

2.7.0+cu128
12.8


True

### INTRODUCTION TO TENSORS
Pytorch tensors are creaties using `torch.tensor()` : *https://docs.pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor*

Tensors can be broken down into 4 categories so far:
* **scalar(x)** is 0 dimensions, 0 square brackets; a single number; Lower(a)
* **vector([x, x])** is 1 dimension, 1 square brackets; a number with direction. i.e wind speed & direction, may have more numbers; Lower(y)
* **MATRIX([[x, x], [x, x]])** is 2 dimensions, 2 square brackets; 2 dimensional array of numbers; Upper(Q)
*  **TENSOR([x, x, x], [x, x, x], [x, x, x])** is n dimensions, n square brackets; 0 dimensional tensor is scalar, 1 dimension is vector, 2 dimension is matrix; Upper(X)

In [8]:
# Scalar
scalar = torch.tensor(7) # torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) → Tensorr
scalar

tensor(7)

In [9]:
scalar.ndim

# 0 dimensions because no brackets

0

In [10]:
# Get tensor back as Python int
scalar.item()

7

In [11]:
scalar.shape

torch.Size([])

In [12]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [13]:
vector.ndim

# 1 dimension bc 1 bracket pair ...([x, x])

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX

MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

# 2 dimensions bc 2 bracket pairs, ...([[x, x], [x, x])

2

In [17]:
MATRIX[0]

tensor([7, 8])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
# TENSOR

TENSOR = torch.tensor([[[1, 2 , 3, 1, 2], 
                        [3, 6, 9, 2, 3], 
                        [2, 4, 5, 3, 3],
                        [7, 5, 3, 4, 3]]])

TENSOR

tensor([[[1, 2, 3, 1, 2],
         [3, 6, 9, 2, 3],
         [2, 4, 5, 3, 3],
         [7, 5, 3, 4, 3]]])

In [20]:
TENSOR.ndim

# 3 dimensions bc 3 bracket pairs, ...([[[x, x, x], [x, x, x], [x, x, x]]])

3

In [21]:
TENSOR.shape

#torch.Size([1, 4, 5])
# [1, ... Encompases the whole tensor as 1 unit due to all bracket pairs being nested.
#  4, ... Encompases the 4 bracket pairs (Can be any amount of bracket paits as long as more than 1)
#  5] ... Enxompases the 5 integers in each bracket (can be any amount of integers as long as more than 1)

torch.Size([1, 4, 5])

torch.Size([1, y, z])

    - [1, ... Encompases the whole tensor as 1 unit due to all bracket pairs being nested.
    - y, ... Encompases the y bracket pairs (Can be any amount of bracket paits as long as more than 1)
    - z] ... Enxompases the z integers in each bracket (can be any amount of integers as long as more than 1)

In [22]:
TENSOR[0]

tensor([[1, 2, 3, 1, 2],
        [3, 6, 9, 2, 3],
        [2, 4, 5, 3, 3],
        [7, 5, 3, 4, 3]])

### RANDOM TENSORS

Randomized Pytorch tensors are created via `torch.rand()`: *https://docs.pytorch.org/docs/stable/generated/torch.rand.html#torch-rand*

Why random tensors?
* Random tensors are important bc neural networks learn by starting with tensors of random numbers, then adjusting those random numbers to better represent the data.

`Start with random nunbers -> look at daa -> update random numbers -> look at data -> update random numbers`

In [23]:
# Create a random tensor of size/shape (3, 4)
random_TENSOR = torch.rand(3, 4)

random_TENSOR

tensor([[0.3894, 0.6821, 0.5349, 0.1741],
        [0.1984, 0.9944, 0.0748, 0.8477],
        [0.5217, 0.3853, 0.0297, 0.4463]])

In [24]:
# Create a random tensor with similar shape to an image tensor
random_image_size_TENSOR = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)

random_image_size_TENSOR.shape, random_image_size_TENSOR.ndim

(torch.Size([224, 224, 3]), 3)

### ZEROS & ONES

In [25]:
# Create tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros*random_TENSOR

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:
tensor_with_zero_column = random_TENSOR.clone()
tensor_with_zero_column[:, 3] = 0
tensor_with_zero_column

# makes the last column of the random_TENSOR all zeros

tensor([[0.3894, 0.6821, 0.5349, 0.0000],
        [0.1984, 0.9944, 0.0748, 0.0000],
        [0.5217, 0.3853, 0.0297, 0.0000]])

### CREATING A RANGE OF TENSORS & TENSORS-LIKE

In [30]:
# Use torch.arange(start, end, step) to create a range of numbers
one_to_ten = torch.arange(0, 11, 1)
one_to_ten, one_to_ten.flip(0) # reverses range


(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0]))

In [31]:
# Creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### TENSOR DATATYPES

Tensor datatypes are one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [32]:
# FLoat 32 tensor
float_32_tensor = torch.tensor([3.3, 6.6, 9.9], 
                               dtype=None, # what datatype is the tensor; defaults to float32 if not specified (e.g float32 or float16) (float16 is half precision to float32)
                                 device=None, # what device the tensor is on; device defaults to CPU if not specified (e.g. 'cpu' or 'cuda:0' for GPU) (e.g. 'cuda:0' for first GPU or 'cuda:1' for second GPU)
                                    requires_grad=False) # whether or not to track gradients with this tensors operations; requires_grad defaults to False if not specified

float_32_tensor

tensor([3.3000, 6.6000, 9.9000])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16) # convert to float16
float_16_tensor



tensor([3.3008, 6.6016, 9.8984], dtype=torch.float16)

In [35]:
float_64_tensor = float_32_tensor.type(torch.float64) # convert to float64
float_64_tensor

tensor([3.3000, 6.6000, 9.9000], dtype=torch.float64)

In [36]:
test = float_32_tensor * float_16_tensor 
test

tensor([10.8926, 43.5703, 97.9945])

In [37]:
float_32_tensor * float_32_tensor # will work because same data type

tensor([10.8900, 43.5600, 98.0100])

In [38]:
float_32_tensor * float_64_tensor # will not because same data type

tensor([10.8900, 43.5600, 98.0100], dtype=torch.float64)

In [39]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32) # create int32 tensor
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [40]:
float_32_tensor * int_32_tensor # will work because int32 can be converted to float32

tensor([ 9.9000, 39.6000, 89.1000])

### GETTING INFORMATION FROM TENSORS (TENSOR ATTRIBUTES)

1. Tensors not right datatype: To get datatype from tensor use, `tensor.dtype`
2. Tensors not right shape: To get shape/size from a tensor use, `tensor.shape`
3. Tensors not right device: To get device from a tensor use, `tensor.device`

In [41]:
# Create a tensor
some_TENSOR = torch.rand(size=(3, 4), device="cuda:0") # create a tensor on the first GPU (if available)
some_TENSOR

tensor([[0.8450, 0.4236, 0.2306, 0.8298],
        [0.3706, 0.9068, 0.2272, 0.1430],
        [0.6642, 0.2659, 0.9943, 0.9842]], device='cuda:0')

In [42]:
# Find out the details about some_TENSOR
print(some_TENSOR)
print(f"Datatype of tensor: {some_TENSOR.dtype}")
print(f"Shape of tensor: {some_TENSOR.shape}")
print(f"Device tensor is on: {some_TENSOR.device}") 

tensor([[0.8450, 0.4236, 0.2306, 0.8298],
        [0.3706, 0.9068, 0.2272, 0.1430],
        [0.6642, 0.2659, 0.9943, 0.9842]], device='cuda:0')
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cuda:0


### MANIPULATING TENSORS (TENSOR OPERATIONS)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (*element-wise*)
* Division
* Matrix Multiplication

In [43]:
# Create a tensor & add 10 to it
TENSOR_1 = torch.tensor([1, 2, 3])
TENSOR_1 + 10

tensor([11, 12, 13])

In [44]:
# Multiplay the tensor by 10
TENSOR_1 * 10

tensor([10, 20, 30])

In [45]:
# Subtract 10 from the tensor
TENSOR_1 - 10

tensor([-9, -8, -7])

In [46]:
# Try out Pytorch in-built functions
torch.mul(TENSOR_1, 10) # multiply by 10

tensor([10, 20, 30])

In [47]:
# Add 10 to the tensor
torch.add(TENSOR_1, 10) 

tensor([11, 12, 13])

### MATRIX MULTIPLICATION

*Two main ways to preform multiplication in neural networks & deep learning:*
1. Element-Wise multiplication
2. Matrix Multiplication (The Dot Product, e.g (a•b))

There are 2 main rules to satisfy when preforming Matrix Multiplication
1. The **inner dimensions** must match:
* `(3,2) @ (3, 2)` won't work
* `(2,3) @ (3, 2)` will work
* `(3,2) @ (2, 3)` will work

2. The resulting Matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [70]:
# Element-Wise multiplication
print(TENSOR_1, '*', TENSOR_1)
print(f"Equals: {TENSOR_1 * TENSOR_1}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [71]:
# Matrix multiplication
torch.matmul(TENSOR_1, TENSOR_1) # tensor([1, 2, 3]) • tensor([1, 2, 3]) dot product


tensor(14)

In [72]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [73]:
# Matrix multiplication by hand with torch
# DONT USE THIS, USE torch.matmul() INSTEAD
%time
value = 0
for i in range(len(TENSOR_1)):
    value += TENSOR_1[i] * TENSOR_1[i]

print(value)


CPU times: total: 0 ns
Wall time: 0 ns
tensor(14)


In [74]:
# USE THIS INSTEAD OF THE ABOVE AND BELOW
%time
torch.matmul(TENSOR_1, TENSOR_1)


CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [75]:
# Matrix multiplication with @ operator
TENSOR_1 @ TENSOR_1 # @ is the same as torch.matmul(), tho less readable

tensor(14)

### COMMON ERROR IN DEEP LEARING: SHAPE ERROR

In [ ]:
# Shape Error
torch.matmul(torch.rand(2, 3), torch.rand(2, 3)) # will throw an error because the inne dimensions don't match for matrix multiplication

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [84]:
# Will work because the inner dimensions match (3 in this case)
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[1.0197, 0.6159, 0.6097],
        [0.3468, 0.4634, 0.0968],
        [0.5049, 0.4776, 0.2267]])

In [94]:
# Shape for Matrix multiplication
TENSOR_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

TENSOR_B = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])                 

torch.matmul(TENSOR_A, TENSOR_B) # will throw an error because the inner dimensions don't match (2 != 3)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [95]:
TENSOR_A.shape, TENSOR_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix a shape issue , we can manipulate the shape of a tensor using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [99]:
TENSOR_B, TENSOR_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [ ]:
# Transpose TENSOR_B to make the inner dimensions match
TENSOR_B.T, TENSOR_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [110]:
# The matrix multiplication operation will now work once Tensor_A or Tensor_B is transposed
print(f"Original shapes: TENSOR_A: {TENSOR_A.shape}, TENSOR_B: {TENSOR_B.shape} \n")
print(f"Transposed shapes: TENSOR_A: {TENSOR_A.shape}, TENSOR_B: {TENSOR_B.T.shape} \n")
print(f"Multiplying: {TENSOR_A.shape} @ {TENSOR_B.T.shape} <-- inner dimensions match \n")

result = torch.matmul(TENSOR_A, TENSOR_B.T)
print(f"Result: \n")
print(result)

print(f"\n Result shape: {result.shape} \n")

Original shapes: TENSOR_A: torch.Size([3, 2]), TENSOR_B: torch.Size([3, 2]) 

Transposed shapes: TENSOR_A: torch.Size([3, 2]), TENSOR_B: torch.Size([2, 3]) 

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <-- inner dimensions match 

Result: 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

 Result shape: torch.Size([3, 3]) 

