In [3]:
print("Hello world, lets start playing with pytorch!")

Hello world, lets start playing with pytorch!


In [199]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)
print(torch.version.cuda)
torch.cuda.is_available()

2.7.0+cu128
12.8


True

In [200]:
!NVIDIA-SMI

Tue Jun  3 19:37:43 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.02                 Driver Version: 576.02         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080      WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   54C    P3             37W /  340W |    3055MiB /  16376MiB |     40%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### INTRODUCTION TO TENSORS
Pytorch tensors are creaties using `torch.tensor()` : *https://docs.pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor*

Tensors can be broken down into 4 categories so far:
* **scalar(x)** is 0 dimensions, 0 square brackets; a single number; Lower(a)
* **vector([x, x])** is 1 dimension, 1 square brackets; a number with direction. i.e wind speed & direction, may have more numbers; Lower(y)
* **MATRIX([[x, x], [x, x]])** is 2 dimensions, 2 square brackets; 2 dimensional array of numbers; Upper(Q)
*  **TENSOR([x, x, x], [x, x, x], [x, x, x])** is n dimensions, n square brackets; 0 dimensional tensor is scalar, 1 dimension is vector, 2 dimension is matrix; Upper(X)

In [5]:
# Scalar
scalar = torch.tensor(7) # torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) → Tensorr
scalar

tensor(7)

In [6]:
scalar.ndim

# 0 dimensions because no brackets

0

In [7]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
scalar.shape

torch.Size([])

In [9]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

# 1 dimension bc 1 bracket pair ...([x, x])

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX

MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

# 2 dimensions bc 2 bracket pairs, ...([[x, x], [x, x])

2

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# TENSOR

TENSOR = torch.tensor([[[1, 2 , 3, 1, 2], 
                        [3, 6, 9, 2, 3], 
                        [2, 4, 5, 3, 3],
                        [7, 5, 3, 4, 3]]])

TENSOR

tensor([[[1, 2, 3, 1, 2],
         [3, 6, 9, 2, 3],
         [2, 4, 5, 3, 3],
         [7, 5, 3, 4, 3]]])

In [17]:
TENSOR.ndim

# 3 dimensions bc 3 bracket pairs, ...([[[x, x, x], [x, x, x], [x, x, x]]])

3

In [18]:
TENSOR.shape

#torch.Size([1, 4, 5])
# [1, ... Encompases the whole tensor as 1 unit due to all bracket pairs being nested.
#  4, ... Encompases the 4 bracket pairs (Can be any amount of bracket paits as long as more than 1)
#  5] ... Enxompases the 5 integers in each bracket (can be any amount of integers as long as more than 1)

torch.Size([1, 4, 5])

torch.Size([1, y, z])

    - [1, ... Encompases the whole tensor as 1 unit due to all bracket pairs being nested.
    - y, ... Encompases the y bracket pairs (Can be any amount of bracket paits as long as more than 1)
    - z] ... Enxompases the z integers in each bracket (can be any amount of integers as long as more than 1)

In [19]:
TENSOR[0]

tensor([[1, 2, 3, 1, 2],
        [3, 6, 9, 2, 3],
        [2, 4, 5, 3, 3],
        [7, 5, 3, 4, 3]])

### RANDOM TENSORS

Randomized Pytorch tensors are created via `torch.rand()`: *https://docs.pytorch.org/docs/stable/generated/torch.rand.html#torch-rand*

Why random tensors?
* Random tensors are important bc neural networks learn by starting with tensors of random numbers, then adjusting those random numbers to better represent the data.

`Start with random nunbers -> look at daa -> update random numbers -> look at data -> update random numbers`

In [20]:
# Create a random tensor of size/shape (3, 4)
random_TENSOR = torch.rand(3, 4)

random_TENSOR

tensor([[0.7107, 0.2933, 0.2982, 0.5578],
        [0.0533, 0.5855, 0.2348, 0.9792],
        [0.3530, 0.3641, 0.9924, 0.5023]])

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_TENSOR = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)

random_image_size_TENSOR.shape, random_image_size_TENSOR.ndim

(torch.Size([224, 224, 3]), 3)

### ZEROS & ONES

In [22]:
# Create tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_TENSOR

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
tensor_with_zero_column = random_TENSOR.clone()
tensor_with_zero_column[:, 3] = 0
tensor_with_zero_column

# makes the last column of the random_TENSOR all zeros

tensor([[0.7107, 0.2933, 0.2982, 0.0000],
        [0.0533, 0.5855, 0.2348, 0.0000],
        [0.3530, 0.3641, 0.9924, 0.0000]])

### CREATING A RANGE OF TENSORS & TENSORS-LIKE

In [27]:
# Use torch.arange(start, end, step) to create a range of numbers
one_to_ten = torch.arange(0, 11, 1)
one_to_ten, one_to_ten.flip(0) # reverses range


(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0]))

In [28]:
# Creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### TENSOR DATATYPES

Tensor datatypes are one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [29]:
# FLoat 32 tensor
float_32_tensor = torch.tensor([3.3, 6.6, 9.9], 
                               dtype=None, # what datatype is the tensor; defaults to float32 if not specified (e.g float32 or float16) (float16 is half precision to float32)
                                 device=None, # what device the tensor is on; device defaults to CPU if not specified (e.g. 'cpu' or 'cuda:0' for GPU) (e.g. 'cuda:0' for first GPU or 'cuda:1' for second GPU)
                                    requires_grad=False) # whether or not to track gradients with this tensors operations; requires_grad defaults to False if not specified

float_32_tensor

tensor([3.3000, 6.6000, 9.9000])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16) # convert to float16
float_16_tensor



tensor([3.3008, 6.6016, 9.8984], dtype=torch.float16)

In [32]:
float_64_tensor = float_32_tensor.type(torch.float64) # convert to float64
float_64_tensor

tensor([3.3000, 6.6000, 9.9000], dtype=torch.float64)

In [33]:
test = float_32_tensor * float_16_tensor 
test

tensor([10.8926, 43.5703, 97.9945])

In [34]:
float_32_tensor * float_32_tensor # will work because same data type

tensor([10.8900, 43.5600, 98.0100])

In [35]:
float_32_tensor * float_64_tensor # will not because same data type

tensor([10.8900, 43.5600, 98.0100], dtype=torch.float64)

In [36]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32) # create int32 tensor
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor # will work because int32 can be converted to float32

tensor([ 9.9000, 39.6000, 89.1000])

### GETTING INFORMATION FROM TENSORS (TENSOR ATTRIBUTES)

1. Tensors not right datatype: To get datatype from tensor use, `tensor.dtype`
2. Tensors not right shape: To get shape/size from a tensor use, `tensor.shape`
3. Tensors not right device: To get device from a tensor use, `tensor.device`

In [38]:
# Create a tensor
some_TENSOR = torch.rand(size=(3, 4), device="cuda:0") # create a tensor on the first GPU (if available)
some_TENSOR

tensor([[0.6655, 0.0756, 0.2046, 0.4797],
        [0.1260, 0.1927, 0.9101, 0.4148],
        [0.9483, 0.8523, 0.4945, 0.2175]], device='cuda:0')

In [39]:
# Find out the details about some_TENSOR
print(some_TENSOR)
print(f"Datatype of tensor: {some_TENSOR.dtype}")
print(f"Shape of tensor: {some_TENSOR.shape}")
print(f"Device tensor is on: {some_TENSOR.device}") 

tensor([[0.6655, 0.0756, 0.2046, 0.4797],
        [0.1260, 0.1927, 0.9101, 0.4148],
        [0.9483, 0.8523, 0.4945, 0.2175]], device='cuda:0')
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cuda:0


### MANIPULATING TENSORS (TENSOR OPERATIONS)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (*element-wise*)
* Division
* Matrix Multiplication

In [40]:
# Create a tensor & add 10 to it
TENSOR_1 = torch.tensor([1, 2, 3])
TENSOR_1 + 10

tensor([11, 12, 13])

In [41]:
# Multiplay the tensor by 10
TENSOR_1 * 10

tensor([10, 20, 30])

In [42]:
# Subtract 10 from the tensor
TENSOR_1 - 10

tensor([-9, -8, -7])

In [43]:
# Try out Pytorch in-built functions
torch.mul(TENSOR_1, 10) # multiply by 10

tensor([10, 20, 30])

In [44]:
# Add 10 to the tensor
torch.add(TENSOR_1, 10) 

tensor([11, 12, 13])

### MATRIX MULTIPLICATION

*Two main ways to preform multiplication in neural networks & deep learning:*
1. Element-Wise multiplication
2. Matrix Multiplication (The Dot Product, e.g (a•b))

There are 2 main rules to satisfy when preforming Matrix Multiplication
1. The **inner dimensions** must match:
* `(3,2) @ (3, 2)` won't work
* `(2,3) @ (3, 2)` will work
* `(3,2) @ (2, 3)` will work

2. The resulting Matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [45]:
# Element-Wise multiplication
print(TENSOR_1, '*', TENSOR_1)
print(f"Equals: {TENSOR_1 * TENSOR_1}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [46]:
# Matrix multiplication
torch.matmul(TENSOR_1, TENSOR_1) # tensor([1, 2, 3]) • tensor([1, 2, 3]) dot product


tensor(14)

In [47]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [48]:
# Matrix multiplication by hand with torch
# DONT USE THIS, USE torch.matmul() INSTEAD
%time
value = 0
for i in range(len(TENSOR_1)):
    value += TENSOR_1[i] * TENSOR_1[i]

print(value)


CPU times: total: 0 ns
Wall time: 0 ns
tensor(14)


In [49]:
# USE THIS INSTEAD OF THE ABOVE AND BELOW
%time
torch.matmul(TENSOR_1, TENSOR_1)


CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [50]:
# Matrix multiplication with @ operator
TENSOR_1 @ TENSOR_1 # @ is the same as torch.matmul(), tho less readable

tensor(14)

### COMMON ERROR IN DEEP LEARING: SHAPE ERROR

In [51]:
# Shape Error
torch.matmul(torch.rand(2, 3), torch.rand(2, 3)) # will throw an error because the inne dimensions don't match for matrix multiplication

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
# Will work because the inner dimensions match (3 in this case)
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[1.0197, 0.6159, 0.6097],
        [0.3468, 0.4634, 0.0968],
        [0.5049, 0.4776, 0.2267]])

In [ ]:
# Shape for Matrix multiplication
TENSOR_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

TENSOR_B = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])                 

torch.matmul(TENSOR_A, TENSOR_B) # will throw an error because the inner dimensions don't match (2 != 3)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
TENSOR_A.shape, TENSOR_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix a shape issue , we can manipulate the shape of a tensor using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
TENSOR_B, TENSOR_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [ ]:
# Transpose TENSOR_B to make the inner dimensions match
TENSOR_B.T, TENSOR_B.T.shape

NameError: name 'TENSOR_B' is not defined

In [ ]:
# The matrix multiplication operation will now work once Tensor_A or Tensor_B is transposed
print(f"Original shapes: TENSOR_A: {TENSOR_A.shape}, TENSOR_B: {TENSOR_B.shape} \n")
print(f"Transposed shapes: TENSOR_A: {TENSOR_A.shape}, TENSOR_B: {TENSOR_B.T.shape} \n")
print(f"Multiplying: {TENSOR_A.shape} @ {TENSOR_B.T.shape} <-- inner dimensions match \n")

result = torch.matmul(TENSOR_A, TENSOR_B.T)
print(f"Result: \n")
print(result)

print(f"\n Result shape: {result.shape} \n")

Original shapes: TENSOR_A: torch.Size([3, 2]), TENSOR_B: torch.Size([3, 2]) 

Transposed shapes: TENSOR_A: torch.Size([3, 2]), TENSOR_B: torch.Size([2, 3]) 

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <-- inner dimensions match 

Result: 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

 Result shape: torch.Size([3, 3]) 



### FINDING THE MIN, MAX, MEAN, SUM, ETC. OF A TENSOR (TENSOR AGGREGATION)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min() # returns the minimum value in the tensor

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max() # returns the maximum value in the tensor

(tensor(90), tensor(90))

In [ ]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # returns the mean of the tensor (must convert to float or complex number first)

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum() # returns the sum of the tensor

(tensor(450), tensor(450))

### FINDING THE POSITIONAL MIN & MAX

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Returns the index of the minimum value in the tensor
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Returns the index of the maximum value in the tensor
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

In [ ]:
# Returns the minimum value in the tensor
x[x.argmin()] 

tensor(1)

### RESHAPING, STACKING, SQUEEZING, & UNSQUEEZING TENSORS

* Reshaping - Reshapes an input tensor to a defined shape.
* View - Returns a view of an input tensor of a certain shape, but keeps the shape of the tensor
* Stacking - Combine multiple tensors on top of eachother (vstack) or side by side (hstack).
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimention to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [ ]:
x = torch.arange(1., 10, 1)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension to the tensor (Must be a multiple of the original tensor's shape)
x_reshaped = x.reshape(1, 9) # Reshape the tensor to have 1 row and 9 columns

x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view of the tensor
z = x.view(1, 9) # View the tensor as having 9 rows and 1 columns
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because they share the same memory)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # Stack the tensors on top of each other (dim=0 means stack along the first dimension)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [ ]:
# torch.squeeze() removes all dimensions of size 1 from a tensor
#x_reshaped, x_reshaped.shape

print(f"Original tensor: {x_reshaped}", 
      f"\nOriginal tensor shape: {x_reshaped.shape}")

x_squeezed = torch.squeeze(x_reshaped) # Squeeze the tensor to remove all dimensions of size 1
print(f"\nNew tensor: {x_squeezed}", 
      f"\nNew tensor shape: {x_squeezed.shape}")


Original tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
Original tensor shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 
New tensor shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a dimension of size 1 to a tensor at a specified dimension
print(f"Previous tensor: {x_squeezed}",
      f"\nPrevious tensor shape: {x_squeezed.shape}")

# Add a dimension of size 1 to the tensor
x_unsqueezed = x_squeezed.unsqueeze(dim=0) 
#x_unsqueezed = torch.unsqueeze(x_squeezed, dim=0)
print(f"\nNew tensor: {x_unsqueezed}",
      f"\nNew tensor shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 
Previous tensor shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
New tensor shape: torch.Size([1, 9])


In [ ]:
# Squeeze the tensor to remove all dimensions of size 1
x_reshaped.squeeze(), x_reshaped.squeeze().shape # Removes the first dimension of size 1 (First square bracket pair)

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# torch.permute() - rearranges the dimensions of a tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color channels (R, G, B)]

# Permute the original tensor to rearragne the axis (or dimension) order
x_permuted = x_original.permute(2, 0, 1) # [color channels (R, G, B), height, width]
print(f"Original tensor shape: {x_original.shape}",
      f"\nPermuted tensor shape: {x_permuted.shape}")

Original tensor shape: torch.Size([224, 224, 3]) 
Permuted tensor shape: torch.Size([3, 224, 224])


In [ ]:
x_original

tensor([[[0.2266, 0.5740, 0.5148],
         [0.4660, 0.7795, 0.7556],
         [0.2197, 0.2516, 0.5751],
         ...,
         [0.9600, 0.6426, 0.5453],
         [0.9086, 0.8184, 0.0790],
         [0.8952, 0.7947, 0.2273]],

        [[0.7873, 0.1554, 0.4412],
         [0.5066, 0.3422, 0.7456],
         [0.1133, 0.2515, 0.1239],
         ...,
         [0.2418, 0.2672, 0.8565],
         [0.7557, 0.0580, 0.2482],
         [0.3169, 0.1066, 0.8245]],

        [[0.3290, 0.8507, 0.9695],
         [0.2614, 0.9304, 0.1081],
         [0.7538, 0.7934, 0.2051],
         ...,
         [0.8108, 0.9690, 0.1073],
         [0.8097, 0.5157, 0.4236],
         [0.1917, 0.8679, 0.2034]],

        ...,

        [[0.3184, 0.1237, 0.2681],
         [0.5060, 0.2082, 0.2176],
         [0.1571, 0.5054, 0.9729],
         ...,
         [0.8451, 0.4620, 0.2496],
         [0.7199, 0.4451, 0.8637],
         [0.9146, 0.8082, 0.3072]],

        [[0.4818, 0.4199, 0.3548],
         [0.7362, 0.1898, 0.6271],
         [0.

In [ ]:
print(f"R: {x_original[0, 0, 0]}") # Access the first pixel's red channel value
print(f"G: {x_original[0, 0, 1]}") # Access the first pixel's green channel value
print(f"B: {x_original[0, 0, 2]}") # Access the first pixel's blue channel value

print(f"?: {x_original[1, 1, 1]}") # Access the second pixel's red channel value
print(f"?: {x_original[2, 2, 2]}") # Access the third pixel's green channel value

print(f"2nd px blue value: {x_original[1, 0, 2]}") # Access the second pixel's blue channel value
print(f"2nd px green value: {x_original[1, 0, 1]}") # Access the second pixel's green channel value
print(f"2nd px red value: {x_original[1, 0, 0]}")

R: 0.22657257318496704
G: 0.5740078687667847
B: 0.5148017406463623
?: 0.3422279953956604
?: 0.20510190725326538
2nd px blue value: 0.44124460220336914
2nd px green value: 0.15536683797836304
2nd px red value: 0.7872782945632935


In [ ]:
x_original[0,0,0] = 2266
x_original[0,0,0], x_permuted[0,0,0] # Access the first pixel's red channel value after changing it

(tensor(2266.), tensor(2266.))

### INDEXING (SELECTING DATA FROM TENSORS)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor

x = torch.arange(1, 10, 1).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Index the new tensor
x[0], x[0].shape # Access the first element of the tensor (in this case, the first tensor).

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
# Index on the middle bracket, or dim=1
x[0][0], x[0][0].shape # Access the first element of the first element of the tensor (in this case, the first tensor -> the first row).

(tensor([1, 2, 3]), torch.Size([3]))

In [ ]:
# Index the most inner bracket, or dim=2 (last bracket/dimension)
x[0][0][0], x[0][0][0].shape # Access the first element of the first element of the first element of the tensor (in this case, the first tensor -> the first row -> first element).

(tensor(1), torch.Size([]))

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:,0] # Access all elements of the first dimension (in this case, the first row of the tensor)

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimension but only index 1 of the 2nd dimension.
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only index 1 of the 1st and 2nd dimension.
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of the 0th and 1st dimension and all values of the 2nd dimension.
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0, 2, 2] # 0th dimension, index 2 on row, index 2 on column

tensor(9)

In [ ]:
# Index on x to return 3, 6, 9
x[0, :, 2] # 0th dimension, all rows, index 2 on column

tensor([3, 6, 9])

### PYTORCH TENSORS & NUMPY

NumPy is a popular scientific  Python numerical computing library. Because of this, PyTorch has functionality to interact with it.
* Data in NumPy -> PyTorch tensor: `torch.from_numpy(ndarray)`
* PyTorch tensor -> data in NumPy: `torch.tensor.numpy()`

In [ ]:
# NumPy array to tensor
array = np.arange(1.0, 8.0, 1.0)
tensor = torch.from_numpy(array) # WARNING: NumPy defaults to float64, PyTorch defaults to float32. Must convert either to match.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what will this do to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### REPRODUCIBILITY (TAKING THE RANDOM OUT OF RANDOM)

In short how neural netwrk learns:
`start with random numbers -> tensor operations -> update random numbers to represent data better -> again -> again -> again...` 

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**, which is implimented with `torch.manual_seed()` and is typically active for 1 subsequent line.

Essentially, what a random seed does is "flavor" the randomness.

In [181]:
import torch

# Create 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Random tensor A: \n{random_tensor_A}\n")
print(f"Random tensor B: \n{random_tensor_B}\n")

print(random_tensor_A == random_tensor_B)


Random tensor A: 
tensor([[0.4493, 0.6423, 0.4923, 0.7285],
        [0.3245, 0.6508, 0.8924, 0.0887],
        [0.9698, 0.5627, 0.4893, 0.9633]])

Random tensor B: 
tensor([[0.9475, 0.6314, 0.0067, 0.4262],
        [0.9859, 0.3940, 0.4951, 0.5961],
        [0.8737, 0.8695, 0.4667, 0.2273]])

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [198]:
# Random but reproducible tensors
import torch

# Set the random seed for reproducibility
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Random tensor C: \n{random_tensor_C}\n")
print(f"Random tensor D: \n{random_tensor_D}\n")

print(random_tensor_C == random_tensor_D)

Random tensor C: 
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])

Random tensor D: 
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### RUNNING TENSORS & PYTORCH OBJECTS ON THE GPU (MAKING FASTER COMPUTATIONS)
CUDA semantics: https://docs.pytorch.org/docs/stable/notes/cuda.html#cuda-semantics

GPUs = faster computation on numbers due to CUDA + NVIDIA Hardware + PyTorch backend.
* Best practice to set up device agnostic code, e.g run on GPU if available, else CPU

In [204]:
# Check if GPU is available
torch.cuda.is_available()


True

In [216]:
# Setup device-agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda


In [207]:
# Count the number of devices available
torch.cuda.device_count()

1

### PUTTING TENSORS (OR MODELS) ON THE GPU

Because its faster.

In [214]:
# Create a tensor (defaults to CPU)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(f"Tensor on device: {tensor.device}")

Tensor on device: cpu


In [ ]:
# Move tensor to GPU if available.
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### MOVING TENSORS BACK TO CPU


In [219]:
# If tensor is on GPU, cannot transmform into NumPy
tensor_on_gpu.numpy() # Will throw an error if tensor is on GPU

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [220]:
# To fix GPU tensor to NumPy, move it back to CPU first
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy() # Move tensor back to CPU and convert to NumPy
tensor_back_on_cpu

array([1, 2, 3])

In [221]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')