In [5]:
print("Hello world, lets start playing with pytorch!")

Hello world, lets start playing with pytorch!


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)
print(torch.version.cuda)
torch.cuda.is_available()

2.7.0+cu128
12.8


True

INTRODUCTION TO TENSORS
    - Pytorch tensors are creaties using 'torch.tensor()' : https://docs.pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor
    - Tensors can be broken down into 4 categories so far, scalar(x), vector([x, x]), MATRIX([[x, x], [x, x]]), TENSOR([x, x, x], [x, x, x], [x, x, x])
        - scalar is 0 dimensions, 0 square brackets
        - vector is 1 dimension, 1 square brackets
        - MATRIX is 2 dimensions, 2 square brackets
        - TENSOR is 3 dimensions, 3+ square brackets

In [26]:
# Scalar
scalar = torch.tensor(7) # torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) → Tensorr
scalar

tensor(7)

In [ ]:
scalar.ndim

# 0 dimensions because no brackets

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [27]:
scalar.shape

torch.Size([])

In [29]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

# 1 dimension bc 1 bracket pair ...([x, x])

1

In [28]:
vector.shape

torch.Size([2])

In [18]:
# MATRIX

MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

# 2 dimensions bc 2 bracket pairs, ...([[x, x], [x, x])

2

In [50]:
MATRIX[0]

tensor([7, 8])

In [30]:
MATRIX.shape

torch.Size([2, 2])

In [92]:
# TENSOR

TENSOR = torch.tensor([[[1, 2 , 3, 1, 2], 
                        [3, 6, 9, 2, 3], 
                        [2, 4, 5, 3, 3],
                        [7, 5, 3, 4, 3]]])

TENSOR

tensor([[[1, 2, 3, 1, 2],
         [3, 6, 9, 2, 3],
         [2, 4, 5, 3, 3],
         [7, 5, 3, 4, 3]]])

In [93]:
TENSOR.ndim

# 3 dimensions bc 3 bracket pairs, ...([[[x, x, x], [x, x, x], [x, x, x]]])

3

In [ ]:
TENSOR.shape

#torch.Size([1, 4, 5])
# [1, ... Encompases the whole tensor as 1 unit due to all bracket pairs being nested.
#  4, ... Encompases the 4 bracket pairs (Can be any amount of bracket paits as long as more than 1)
#  5] ... Enxompases the 5 integers in each bracket (can be any amount of integers as long as more than 1)

torch.Size([1, 4, 5])

In [91]:
TENSOR[0]

tensor([[1, 2, 3, 1, 2]])